#!/bin/bash

echo '''#!/bin/sh
# Generated by /opt/aws-ss/server-start_gen.sh
echo "server-start: starting shadowsocks server(s)..."''' | sudo tee /opt/shadowsocks/server-start.sh

for filename in /opt/shadowsocks/ss-server_*.conf; do
    [ -e "$filename" ] || continue
    port=$(echo $filename | sed -n 's/.*_\(.*\)\.conf/\1/p')
    echo "/usr/local/bin/ss-server -c /opt/shadowsocks/ss-server_$port.conf -f /opt/shadowsocks/pid/ss-server_$port.pid" | sudo tee --append /opt/shadowsocks/server-start.sh
done