#!/bin/bash

echo '''#!/bin/sh
# Generated by /opt/aws-ss/server-start_gen.sh
echo "server-start: starting shadowsocks server(s)..."''' | sudo tee /opt/shadowsocks/server-start.sh

for filename in /opt/shadowsocks/client-url_*.txt; do
    [ -e "$filename" ] || continue
    port=$(echo $filename | sed -n 's/.*_\(.*\)\.txt/\1/p')
    openssl aes-256-cbc -in $filename -out /tmp/tmp.enc -pass file:/home/ec2-user/aws-ss-config/config_password.tmp
    echo "<div class='container'><div class='blob'>$(cat /tmp/tmp.enc | xxd -p -c 9999)</div></div>" | sudo tee /opt/shadowsocks/$port.enc
    rm /tmp/tmp.enc
    echo "/usr/local/bin/ss-server -c /opt/shadowsocks/ss-server_$port.conf -f /opt/shadowsocks/pid/ss-server_$port.pid" | sudo tee --append /opt/shadowsocks/server-start.sh
done

blobs=$(cat /opt/shadowsocks/*.enc | tr -d '\n')
sed -e "s|INPUT_FROM_GENERATOR|${blobs}|" /opt/aws-ss/s3-config-website/index_template.html | sudo tee /opt/shadowsocks/index.html

s3bucket=$(cat /home/ec2-user/aws-ss-config/s3_bucket.txt | tr -d '\n')

aws s3 cp /opt/aws-ss/s3-config-website/crypto-js.min.js s3://$s3bucket --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
aws s3 cp /opt/aws-ss/s3-config-website/jquery-3.3.1.min.js s3://$s3bucket --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
aws s3 cp /opt/shadowsocks/index.html s3://$s3bucket --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers